### ISSUE TITLE
Mean Centred Task Analysis - mctype 3 data shape error for single condition data

### ISSUE THREAD

**Issue by justinliuyuwang** [McIntosh-Lab/plspy#13]
Hello! I’m trying to run mct pls with mctype 3. My parameters and datashape work fine for mctype 0 and 1 but error out with mctype 3. Below is the code I ran. Thank you!

### Reproducing code example

```python

import plspy
import numpy as np
import pandas as pd

#load subjects and cluster labels from tsv
b=pd.read_csv("<path>/<to>/<labels>.tsv", delimiter="\t")

#load subjects and FC matrices from tsv
a=pd.read_csv("<path>/<to>/<FC>.tsv", delimiter="\t")


#merge FC df and labels df
joint=pd.merge(a,b, on="sub")


#triu FCs to flat array
mytriu=np.triu_indices(420)
joint['triu'] = joint.apply(lambda row : np.nan_to_num(row["FC"].reshape((420,420))[mytriu]), axis = 1)



#find num subs of each label
occur = joint.groupby(['label']).size()
print(occur)


#only take labels 0,1,2 (clusters) and first 64 subs of each group
final0=joint.loc[joint['label'] == 0]
final1=joint.loc[joint['label'] == 1]
final2=joint.loc[joint['label'] == 2]
final0 = final0.head(64)
final1 = final1.head(64)
final2 = final2.head(64)

#stack subs
tostack = pd.concat([final0,final1,final2])

#X is array (not df) of triu field only
tostack=tostack.loc[tostack['label'] != 4]['triu']
X=np.array(tostack.values.tolist()) #.squeeze()
X=X.astype(np.float64)

#second parameter is hardcoded group sizes
plspy.PLS(X, [64, 64, 64], 1, num_perm=500, num_boot=500,  pls_method="mct", mctype=3)

```

### Error message

>>> plspy.PLS(X, [64, 64, 64], 1, num_perm=500, num_boot=500,  pls_method="mct", mctype=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/jwangbay/ADNI3_FC/ENV/lib/python3.8/site-packages/plspy/core/pls.py", line 63, in PLS
    return pls_classes.PLSBase._create(pls_method, *args, **kwargs)
  File "/scratch/jwangbay/ADNI3_FC/ENV/lib/python3.8/site-packages/plspy/core/pls_classes.py", line 71, in _create
    return cls._subclasses[pls_method](*args, **kwargs)
  File "/scratch/jwangbay/ADNI3_FC/ENV/lib/python3.8/site-packages/plspy/core/pls_classes.py", line 237, in __init__
    self.X_means, self.X_mc = class_functions._mean_centre(
  File "/scratch/jwangbay/ADNI3_FC/ENV/lib/python3.8/site-packages/plspy/core/class_functions.py", line 87, in _mean_centre
    X_mc = X - x_repeats - gm_repeats
ValueError: operands could not be broadcast together with shapes (192,88410) (576,88410)

### plspy/Python version information

0+unknown 3.8.10 (default, Jun 16 2021, 14:20:20) 
[GCC 9.3.0]

**Comment by justinliuyuwang** [comment]
Some insight maybe from the MATLAB implementation. When mctype 0,2, or 3 are selected for single-condition data, this message is given to the user:

```
Because you are running single condition Task PLS, input
Mean-Centering Type has to reset to 1.
```

It looks like only mean-centering type 1 needs to be supported for single-condition data, and any attempts by users
to use other types should default in type 1 being run.

**Comment by justinliuyuwang** [comment]
Recommended fix for plspy: default to type 1 if type 0,2,3 are selected for single condition data

**Comment by lrokos** [comment]
Default to type 1 for single-condition data implemented with commit cdf91de
